# -*- Coding: UTF-8 -*-
#coding: utf-8

#linhas   = 'CD_TELEVENDA,CD_FILIAL,CD_TIPO_CARTAO,CD_ORIGEM_TELEVENDA,CD_MOTIVO_TELEVENDA,CD_OPERADOR,NR_CEP,NR_ROT_DIST,CD_BANDEIRA_CARTAO,CD_FORMA_PAGTO,CD_ENTREGADOR,ID_CLIENTE,NR_ENDERECO,CD_STATUS_TELEVENDA,FL_CONVENIO,NR_PEDIDO,NR_SEQ_PEDIDO,DT_PEDIDO,DTHR_PEDIDO,QT_TOTAL,QT_TOTAL_MEDICAMENTO,QT_TOTAL_PERFUMARIA,VL_TOTAL,VL_DESC_OFERTA,PC_DESC,VL_DESC_CARTAO,VL_DESC_FAIXA1,VL_TOTAL_LIQUIDO,VL_FRETE,FL_FRETE_LIBERADO,FL_ORCAMENTO,VL_TOTAL_PEDIDO,FL_AGENDA,QT_PONTOS,HR_ATEND_PREVISTO,HR_IMPRESSAO,DT_FATURA,HR_FATURA,HR_SAIDA_ENTREGA,HR_ENTREGA,CD_OPERADOR_FATURA,VL_TROCO,NR_CUPOM,CD_BANCO_CHEQUE,NR_ROMANEIO_ENTREGA,VL_DINHEIRO,HR_RETORNO_ENTREGA,NR_CHEQUE,NR_CARTAO_CREDITO,NM_RECEBEU,NR_CONTA_CORRENTE,NR_CPF_CHEQUE,NR_RG_RECEBEU,MM_VALIDADE_CARTAO_CREDITO,AA_VALIDADE_CARTAO_CREDITO,FL_MANUTENCAO,DS_OBS,CD_JANELA_PDV,CD_JANELA_APOIO,CD_TELEVENDA_PAI,DT_CHEQUE,FL_ENDERECO_NOVO,CD_CMC7_CHEQUE,NR_SEQUENCIA_CUPOM,NR_DEPENDENTE_IDADE,VL_REPASSE,CD_FILIAL_ORIGEM_PEDIDO,QT_ROTEIRIZACAO,FL_AGUARDANDO_BAIXA,NR_CODIGO_SEGURANCA,CD_TIPO_TRANS_CARTAO,CD_OPERADOR_BAIXA,NR_RELATORIO_SANGRIA,VL_DIFERENCA_BAIXA,VL_DIFERENCA_DEVOL_CLIENTE,DS_OBS_DIF_BAIXA,VL_NF_DEVOLUCAO,ST_RETIRA_CAIXA,FL_DEVOLUCAO,CD_OPERADOR_SANGRIA,DT_SANGRIA,FL_ESCANEADO,DS_NSU,DT_TRANSACAO_TEF,DS_NSU_CANCELAMENTO,FL_IMPRIMIR_OFFLINE,NR_AUTORIZACAO_PBM,CD_CANAL_INTERNET,NR_PEDIDO_DEVOLUCAO,VL_ABATIMENTO,VL_ARREDONDAMENTO,VL_GORJETA,VL_SUBSIDIO_EMPRESA,FL_AGUARDANDO_PED_VENDA,VL_ABATIMENTO_VISTA,QT_PARCELAS,NR_OBJETO,CD_OPERADOR_MODALIDADE,CD_MOTIVO_ABANDONO_TELEVENDA,CD_CARRIER,IP_OPERADOR,MD_DURACAO_ATENDIMENTO_S,NR_AGENCIA,NR_CPF_CNPJ_NOTA,DT_ENVIO_SUPERPOLO,CD_TELEVENDA_TURNO,FL_EMERGENCIAL,VL_CUSTO_FRETE,FL_ACAO_JUDICIAL,\n'
linhas  = '1213,78,2,1,0,8208,9997999,1,,0,,0,1,1,0,1166,0,5/9/2000,5/9/2000 16:51,1,0,1,"5,98","0,93","15,5518",0,0,"5,05","0,01",0,0,"5,06",0,10,,,,,,,,,,,,,,,,,,,,,,,,0,0,,,0,,0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,0,,0\n'
#linhas = '[{"schema": {"type": "struct", "fields": [{"type": "string", "optional": true, "field": "table"}, {"type": "string", "optional": true, "field": "op_type"}, {"type": "string", "optional": true, "field": "op_ts"}, {"type": "string", "optional": true, "field": "current_ts"}, {"type": "string", "optional": true, "field": "pos"}, {"type": "array", "items": {"type": "string", "optional": false}, "optional": true, "field": "primary_keys"}, {"type": "map", "keys": {"type": "string", "optional": false}, "values": {"type": "string", "optional": false}, "optional": true, "field": "tokens"}, {"type": "struct", "fields": [{"type": "NUMBER", "optional": false, "field": "CD_CANAL_VENDA"}, {"type": "VARCHAR2", "optional": false, "field": "DS_CANAL_VENDA"}], "optional": true, "name": "row", "field": "after"}, {"type": "struct", "fields": [{"type": "NUMBER", "optional": false, "field": "CD_CANAL_VENDA"}, {"type": "VARCHAR2", "optional": false, "field": "DS_CANAL_VENDA"}], "optional": true, "name": "row", "field": "after"}], "optional": false, "name": "A_RAIABD.TB_CANAL_VENDA"}, "payload": {"table": "A_RAIABD.TB_CANAL_VENDA", "op_type": "I", "op_ts": "2021-05-03 11:03:28.979510", "current_ts": "2021-05-03 11:03:36.152000", "pos": "000001", "primary_keys": [], "tokens": {"txid": "0.461.22.1119186"}, "before": {}, "after": {"CD_CANAL_VENDA": 7, "DS_CANAL_VENDA": "INTERNET - CAIXA COMPACTOS"}}},\n'
#linhas = '{"schema": {"type": "struct", "fields": [{"type": "string", "optional": true, "field": "table"}, {"type": "string", "optional": true, "field": "op_type"}, {"type": "string", "optional": true, "field": "op_ts"}, {"type": "string", "optional": true, "field": "current_ts"}, {"type": "string", "optional": true, "field": "pos"}, {"type": "array", "items": {"type": "string", "optional": false}, "optional": true, "field": "primary_keys"}, {"type": "map", "keys": {"type": "string", "optional": false}, "values": {"type": "string", "optional": false}, "optional": true, "field": "tokens"}, {"type": "struct", "fields": [{"type": "NUMBER", "optional": false, "field": "CD_CANAL_VENDA"}, {"type": "VARCHAR2", "optional": false, "field": "DS_CANAL_VENDA"}], "optional": true, "name": "row", "field": "after"}, {"type": "struct", "fields": [{"type": "NUMBER", "optional": false, "field": "CD_CANAL_VENDA"}, {"type": "VARCHAR2", "optional": false, "field": "DS_CANAL_VENDA"}], "optional": true, "name": "row", "field": "after"}], "optional": false, "name": "A_RAIABD.TB_CANAL_VENDA"}, "payload": {"table": "A_RAIABD.TB_CANAL_VENDA", "op_type": "I", "op_ts": "2021-05-03 11:03:28.979510", "current_ts": "2021-05-03 11:03:36.152000", "pos": "000001", "primary_keys": [], "tokens": {"txid": "0.461.22.1119186"}, "before": {}, "after": {"CD_CANAL_VENDA": 4, "DS_CANAL_VENDA": "Farmacia Popular"}}},\n'
#linhas = '{"schema": {"type": "struct", "fields": [{"type": "string", "optional": true, "field": "table"}, {"type": "string", "optional": true, "field": "op_type"}, {"type": "string", "optional": true, "field": "op_ts"}, {"type": "string", "optional": true, "field": "current_ts"}, {"type": "string", "optional": true, "field": "pos"}, {"type": "array", "items": {"type": "string", "optional": false}, "optional": true, "field": "primary_keys"}, {"type": "map", "keys": {"type": "string", "optional": false}, "values": {"type": "string", "optional": false}, "optional": true, "field": "tokens"}, {"type": "struct", "fields": [{"type": "NUMBER", "optional": false, "field": "CD_CANAL_VENDA"}, {"type": "VARCHAR2", "optional": false, "field": "DS_CANAL_VENDA"}], "optional": true, "name": "row", "field": "after"}, {"type": "struct", "fields": [{"type": "NUMBER", "optional": false, "field": "CD_CANAL_VENDA"}, {"type": "VARCHAR2", "optional": false, "field": "DS_CANAL_VENDA"}], "optional": true, "name": "row", "field": "after"}], "optional": false, "name": "A_RAIABD.TB_CANAL_VENDA"}, "payload": {"table": "A_RAIABD.TB_CANAL_VENDA", "op_type": "I", "op_ts": "2021-05-03 11:03:28.979510", "current_ts": "2021-05-03 11:03:36.152000", "pos": "000001", "primary_keys": [], "tokens": {"txid": "0.461.22.1119186"}, "before": {}, "after": {"CD_CANAL_VENDA": 7, "DS_CANAL_VENDA": "INTERNET - CAIXA COMPACTOS"}}}\n]'


def write_linha():
    try:
        with open('/home/isaraujo@raiadrogasil.com/Documentos/beam/modulos/input/televenda3.txt',mode='a') as file:
            cont = 0

            while (cont < 5):
                file.write(linhas)
                cont += 1
            # 10000000 13 G
            # 8000000 10 G
            # 1000000 1.3 G
            # 4000000 5.0G
            # 500000 500 M
    except FileNotFoundError:
        print('Arquivo não encontrado...')
    except PermissionError:
        print('permissao negada para escrever...')


if __name__ == "__main__":
    write_linha()


